# Generated by Django 4.1.4 on 2023-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundimg', models.ImageField(upload_to='allimages')),
                ('bgtitle', models.TextField(max_length=1000)),
                ('descriptions', models.CharField(max_length=100)),
                ('homebtn', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastestPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latestImg', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Latesttitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeftContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('copyRight', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('descriptions', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Navitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navitems_1', models.CharField(max_length=20)),
                ('navitems_2', models.CharField(max_length=20)),
                ('navitems_3', models.CharField(max_length=20)),
                ('navitems_4', models.CharField(max_length=20)),
                ('navitems_5', models.CharField(max_length=20)),
                ('navitems_6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Navlogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navlogo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NavLogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='Navsubitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsubitem_1', models.TextField(max_length=100)),
                ('navsubitem_2', models.TextField(max_length=100)),
                ('navsubitem_3', models.TextField(max_length=100)),
                ('navsubitem_4', models.TextField(max_length=100)),
                ('navsubitem_5', models.TextField(max_length=100)),
                ('navsubitem_6', models.TextField(max_length=100)),
            ],
        ),
    ]
