# Generated by Django 4.1.4 on 2023-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(max_length=100)),
                ('title2', models.TextField(max_length=100)),
                ('description1', models.TextField(max_length=250)),
                ('description2', models.TextField(max_length=250)),
                ('img', models.ImageField(upload_to='allimages')),
                ('btn', models.TextField(max_length=20)),
            ],
        ),
    ]
