# Generated by Django 4.1.4 on 2023-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0002_creative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creativestitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
            ],
        ),
    ]
