# Generated by Django 4.1.4 on 2023-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0003_creativestitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurCompleteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('backtitle', models.CharField(max_length=50)),
                ('btn', models.CharField(max_length=10)),
            ],
        ),
    ]
