# Generated by Django 4.1.4 on 2023-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0004_mainservicestitle_ourcompleteservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('subdescription', models.CharField(max_length=400)),
                ('btn', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='allimages')),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='allimages')),
                ('title', models.CharField(max_length=100)),
                ('skillsName1', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=10)),
                ('skillsName2', models.CharField(max_length=100)),
                ('progress2', models.CharField(max_length=10)),
                ('skillsName3', models.CharField(max_length=100)),
                ('progress3', models.CharField(max_length=10)),
                ('skillsName4', models.CharField(max_length=100)),
                ('progress4', models.CharField(max_length=10)),
                ('skillsName5', models.CharField(max_length=100)),
                ('progress5', models.CharField(max_length=10)),
                ('skillsName6', models.CharField(max_length=100)),
                ('progress6', models.CharField(max_length=10)),
                ('skillsName7', models.CharField(max_length=100)),
                ('progress7', models.CharField(max_length=10)),
                ('skillsName8', models.CharField(max_length=100)),
                ('progress8', models.CharField(max_length=10)),
                ('skillsName9', models.CharField(max_length=100)),
                ('progress9', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=100)),
                ('subtitle3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=100)),
                ('subtitle4', models.CharField(max_length=100)),
                ('description4', models.CharField(max_length=100)),
                ('subtitle5', models.CharField(max_length=100)),
                ('description5', models.CharField(max_length=100)),
                ('subtitle6', models.CharField(max_length=100)),
                ('description6', models.CharField(max_length=100)),
            ],
        ),
    ]
